/* Content is authored separately in each language to preserve a natural corporate tone. */
window.DREAMSOFT_TRANSLATIONS = {
  tr: {
    meta: { title: "DreamSoft | Özel Yazılım ve Otomasyon Çözümleri", description: "DreamSoft, işletmelere özel yazılım, entegrasyon ve akıllı otomasyon çözümleri geliştirir.", ogDescription: "İşletmenize özel, ölçeklenebilir yazılım ve akıllı otomasyon çözümleri." },
    a11y: { skip: "Ana içeriğe geç", navigation: "Ana navigasyon", openMenu: "Menüyü aç", closeMenu: "Menüyü kapat", language: "Dil seçimi", backToTop: "Yukarı dön", close: "Kapat" },
    nav: { home: "Ana Sayfa", about: "Hakkımızda", services: "Hizmetler", solutions: "Çözümler", projects: "Projeler", process: "Çalışma Sürecimiz", technologies: "Teknolojiler", contact: "İletişim", quote: "Teklif Al" },
    hero: { eyebrow: "Hayalleri Akıllı Yazılım Çözümlerine Dönüştürüyoruz.", title: "İşletmenize Özel Yazılım ve Akıllı Otomasyon Çözümleri", description: "DreamSoft; işletmelerin süreçlerini hızlandıran, maliyetleri azaltan ve verimliliği artıran özel yazılım, entegrasyon ve otomasyon sistemleri geliştirir.", primary: "Projenizi Anlatın", secondary: "Hizmetleri İnceleyin", visualLabel: "Otomasyon iş akışı paneli", visualOverline: "AKTİF İŞ AKIŞI", visualTitle: "Sipariş Otomasyonu", running: "Çalışıyor", nodeInput: "Yeni Sipariş", nodeCheck: "Veri Kontrolü", nodeSync: "Sistem Eşleme", nodeReport: "Raporlama", metricFlow: "İş akışı durumu", metricSync: "Senkronizasyon", metricErrors: "Hata yönetimi", secure: "GÜVENLİ BAĞLANTI", principles: ["İhtiyaca özel", "Ölçeklenebilir", "Güvenli mimari"] },
    values: { heading: "Temel Değerlerimiz", items: [
      { icon: "↗", title: "İş Süreçlerinde Verimlilik", text: "Manuel adımları azaltan, ekiplerin zamanını yüksek değerli işlere ayırmasını sağlayan sistemler." },
      { icon: "◇", title: "Ölçeklenebilir Yazılım", text: "Yeni kullanıcılar, modüller ve iş hacmiyle birlikte kontrollü biçimde büyüyen mimariler." },
      { icon: "⌾", title: "Güvenli Altyapı", text: "Veri güvenliği, erişim kontrolü ve sürdürülebilir bakım gözetilerek geliştirilen çözümler." },
      { icon: "∞", title: "Uzun Vadeli Teknik Destek", text: "Canlı kullanım sonrasında izleme, bakım ve gelişen ihtiyaçlara yönelik iyileştirme desteği." }
    ]},
    about: { eyebrow: "DREAMSOFT HAKKINDA", title: "Teknolojiyi gerçek iş sonuçlarına dönüştürüyoruz.", lead: "Yalnızca yazılım üretmiyor; operasyonlarınızı anlıyor, darboğazları belirliyor ve işinize uyum sağlayan sürdürülebilir sistemler tasarlıyoruz.", link: "Yaklaşımımızı inceleyin", statement: "Her proje, net bir iş problemiyle başlar ve ölçülebilir değer üreten teknik bir çözümle ilerler.", points: [
      { title: "Proje bazlı yaklaşım", text: "Hazır kalıplar yerine hedeflerinize, kullanıcılarınıza ve mevcut sistemlerinize göre kapsam oluştururuz." },
      { title: "Sürdürülebilir sistemler", text: "Modüler mimari, okunabilir kod ve dokümantasyonla gelecekte geliştirilebilir ürünler tasarlarız." },
      { title: "Şeffaf iletişim", text: "Öncelikler, riskler ve ilerleme hakkında proje boyunca açık ve düzenli iletişim kurarız." },
      { title: "Ölçülebilir iş değeri", text: "Teknik kararları hız, maliyet, hata oranı ve operasyonel görünürlük gibi iş çıktılarıyla ilişkilendiririz." }
    ]},
    services: { eyebrow: "YETKİNLİKLERİMİZ", title: "İhtiyacınıza göre şekillenen teknoloji hizmetleri", lead: "Fikir aşamasından canlı kullanıma, entegrasyondan sürekli iyileştirmeye kadar uçtan uca yazılım desteği.", details: "Detayları Gör", modalEyebrow: "HİZMET DETAYI", modalIntro: "Bu hizmet kapsamında", items: [
      { icon: "{ }", title: "Özel Yazılım Geliştirme", text: "Standart paketlerin karşılamadığı iş gereksinimleri için size özel, modüler ve sürdürülebilir sistemler.", detail: "İş kuralları, kullanıcı rolleri ve operasyonel hedefler analiz edilerek kurumunuza uyumlu bir ürün mimarisi oluşturulur.", bullets: ["İhtiyaç ve kapsam analizi", "Modüler ürün mimarisi", "Test, dokümantasyon ve devreye alma"] },
      { icon: "⌁", title: "İş Süreçleri Otomasyonu", text: "Tekrarlanan görevleri azaltan, onay ve veri akışlarını hızlandıran güvenilir otomasyonlar.", detail: "Manuel iş adımları haritalanır; kural tabanlı akışlar, bildirimler ve sistem bağlantılarıyla kontrollü biçimde otomatikleştirilir.", bullets: ["Süreç haritalama", "Kural ve onay motorları", "İzleme ve hata yönetimi"] },
      { icon: "▱", title: "Web Uygulama Geliştirme", text: "Her cihazda hızlı, erişilebilir ve güvenli çalışan modern iş ve müşteri uygulamaları.", detail: "Yönetim panellerinden müşteri portallarına kadar ölçeklenebilir ve kullanıcı odaklı web uygulamaları tasarlanır.", bullets: ["Responsive kullanıcı arayüzü", "Rol bazlı yönetim panelleri", "Performans ve erişilebilirlik"] },
      { icon: "▯", title: "Mobil Uygulama Geliştirme", text: "Saha ekipleri, müşteriler ve operasyonlar için kullanışlı mobil uygulama deneyimleri.", detail: "İş senaryosuna göre mobil öncelikli, platformlar arası veya platforma özel uygulama yaklaşımı belirlenir.", bullets: ["Mobil ürün tasarımı", "Bildirim ve çevrimdışı akışlar", "API ve cihaz entegrasyonları"] },
      { icon: "⇄", title: "API ve Sistem Entegrasyonları", text: "ERP, CRM, e-ticaret ve üçüncü taraf platformlar arasında kesintisiz veri akışı.", detail: "Farklı platformlar güvenli API'ler, webhook'lar ve veri eşleme katmanlarıyla tek bir iş akışında buluşturulur.", bullets: ["REST API bağlantıları", "Veri eşleme ve senkronizasyon", "Kayıt, izleme ve hata kurtarma"] },
      { icon: "✦", title: "Yapay Zekâ Destekli Çözümler", text: "Belge, metin ve iş verilerini anlamlandıran kontrollü yapay zekâ entegrasyonları.", detail: "Yapay zekânın gerçek değer üretebileceği kullanım alanları belirlenir; güvenlik ve insan kontrolü gözetilerek süreçlere entegre edilir.", bullets: ["Belge ve metin işleme", "Akıllı sınıflandırma ve öneriler", "Mevcut sistemlere AI entegrasyonu"] },
      { icon: "▥", title: "Raporlama ve Yönetim Panelleri", text: "Dağınık verileri anlaşılır göstergelere ve karar destek ekranlarına dönüştüren sistemler.", detail: "Farklı kaynaklardaki veriler bir araya getirilerek role uygun, güncel ve aksiyon alınabilir rapor ekranları hazırlanır.", bullets: ["KPI ve metrik tasarımı", "Etkileşimli dashboard'lar", "Planlı rapor ve bildirimler"] },
      { icon: "◌", title: "Yazılım Bakım ve Teknik Destek", text: "Canlı sistemlerin güvenli, güncel ve iş ihtiyaçlarıyla uyumlu kalmasını sağlayan destek.", detail: "Uygulamalar izlenir, hatalar önceliklendirilir ve değişen ihtiyaçlara göre planlı bakım ile geliştirme yürütülür.", bullets: ["Hata analizi ve düzeltme", "Güvenlik ve bağımlılık güncellemeleri", "Performans ve özellik iyileştirmeleri"] }
    ]},
    automation: { eyebrow: "AKILLI OTOMASYON", title: "Tekrarlanan işleri sistemlere bırakın.", lead: "Manuel adımları, dağınık verileri ve kopuk uygulamaları güvenilir bir iş akışında birleştirerek ekibinize odaklanma alanı açın.", diagramLabel: "Veri girişinden raporlamaya otomasyon akış diyagramı", workflow: "İŞ AKIŞI MİMARİSİ", status: "Sistem aktif", list: ["Daha az manuel işlem ve hata", "Daha hızlı onay ve sonuç süreleri", "Süreçler üzerinde anlık görünürlük", "Sistemler arasında tutarlı veri"], steps: ["Veri Girişi", "İşleme", "Otomasyon Kuralları", "Entegrasyon", "Raporlama"], opportunities: ["Tekrarlanan görev otomasyonu", "Excel ve raporlama otomasyonu", "Belge ve veri işleme", "İş akışı onay sistemleri", "Müşteri yönetimi otomasyonu", "Üretim ve operasyon izleme", "Stok ve sipariş yönetimi", "E-posta ve bildirim otomasyonu", "Muhasebe ve ERP entegrasyonları", "Platformlar arası veri senkronizasyonu"] },
    industries: { eyebrow: "SEKTÖREL ÇÖZÜMLER", title: "Sektörünüzün dinamiklerine uyum sağlayan sistemler", lead: "Standart paketler yerine iş modelinizi, süreçlerinizi ve büyüme hedeflerinizi temel alan çözüm konseptleri.", items: [
      { icon: "▦", title: "Üretim", text: "Üretim planlama, iş emri, kalite kontrol, duruş ve verimlilik izleme sistemleri." },
      { icon: "❉", title: "HVAC ve Mekanik Taahhüt", text: "Teklif, keşif, maliyet, saha ilerleme, ekipman ve bakım takip uygulamaları." },
      { icon: "△", title: "İnşaat", text: "Proje bütçesi, hakediş, tedarik, doküman ve saha koordinasyon sistemleri." },
      { icon: "⇢", title: "Lojistik", text: "Sevkiyat planlama, araç ve rota takibi, teslimat durumu ve operasyon raporlaması." },
      { icon: "▤", title: "Perakende", text: "Stok, sipariş, şube operasyonları, fiyat ve satış verisi yönetimi." },
      { icon: "◇", title: "Profesyonel Hizmetler", text: "Müşteri, proje, görev, zaman, teklif ve faturalama süreçlerini birleştiren platformlar." },
      { icon: "⌑", title: "E-ticaret", text: "Pazaryeri, sipariş, ürün, stok, kargo ve müşteri iletişimi entegrasyonları." },
      { icon: "◫", title: "Küçük ve Orta Ölçekli İşletmeler", text: "Dağınık iş akışlarını uygun kapsamlı, geliştirilebilir dijital sistemlerde birleştiren çözümler." }
    ]},
    projects: { eyebrow: "PROJE YAKLAŞIMLARI", title: "İş problemlerine yönelik örnek çözüm konseptleri", lead: "Aşağıdaki içerikler tamamlanmış müşteri işleri değil, geliştirilebilecek sistemleri açıklayan örnek proje konseptleridir.", label: "Örnek Proje Konsepti", problem: "İş problemi", solution: "Önerilen çözüm", modules: "Temel modüller", technologies: "Olası teknolojiler", benefit: "Beklenen operasyonel fayda", view: "Konsepti İncele", items: [
      { code: "OPS-01", title: "Üretim Takip Sistemi", problem: "İş emirleri, duruşlar ve üretim verilerinin farklı kaynaklarda tutulması.", solution: "Saha verisini merkezi olarak toplayan ve üretim durumunu anlık gösteren web tabanlı platform.", modules: ["İş emirleri", "Duruş ve kalite", "KPI panelleri"], technologies: "React, .NET, PostgreSQL, REST API", benefit: "Daha görünür üretim akışı, hızlı müdahale ve tutarlı performans verisi." },
      { code: "EST-02", title: "Teklif ve Maliyet Hesaplama Yazılımı", problem: "Karmaşık fiyatlandırma kurallarının manuel tablolarla yönetilmesi.", solution: "Ürün, işçilik ve marj kurallarını merkezi olarak yöneten kontrollü teklif uygulaması.", modules: ["Fiyat kütüphanesi", "Maliyet motoru", "Teklif çıktıları"], technologies: "Next.js, Node.js, PostgreSQL", benefit: "Daha hızlı ve tutarlı teklif hazırlama, izlenebilir revizyon süreci." },
      { code: "CRM-03", title: "Müşteri ve Proje Yönetim Platformu", problem: "Müşteri görüşmeleri, görevler ve proje bilgilerinin dağınık kanallarda kalması.", solution: "Satıştan teslimata müşteri ve proje süreçlerini tek çalışma alanında birleştiren sistem.", modules: ["Müşteri kayıtları", "Proje ve görevler", "Aktivite akışı"], technologies: "React, Python, PostgreSQL, Webhooks", benefit: "Ekipler arasında ortak görünürlük ve daha kontrollü müşteri takibi." },
      { code: "INV-04", title: "Stok ve Sipariş Otomasyonu", problem: "Kanallar arasında stok farkları ve geciken sipariş güncellemeleri.", solution: "Stok hareketleriyle sipariş durumlarını platformlar arasında senkronize eden entegrasyon katmanı.", modules: ["Stok hareketleri", "Sipariş yönetimi", "Uyarı kuralları"], technologies: "Node.js, REST API, Webhooks, MySQL", benefit: "Daha az veri girişi, daha tutarlı stok ve daha hızlı sipariş işleme." },
      { code: "SRV-05", title: "Servis ve Bakım Takip Sistemi", problem: "Servis talepleri, ekip atamaları ve bakım geçmişinin merkezi izlenememesi.", solution: "Talep açılışından saha kapanışına kadar servis operasyonunu yöneten mobil uyumlu uygulama.", modules: ["Servis talepleri", "Ekip planlama", "Bakım geçmişi"], technologies: "React, .NET, SQLite, Cloud", benefit: "Daha hızlı planlama, eksiksiz servis kayıtları ve güçlü saha koordinasyonu." },
      { code: "BI-06", title: "Yönetici Raporlama Paneli", problem: "Karar verilerinin farklı dosya ve uygulamalardan geç hazırlanması.", solution: "Temel göstergeleri otomatik toplayan, birleştiren ve role göre sunan karar destek paneli.", modules: ["Veri bağlantıları", "KPI görünümü", "Planlı raporlar"], technologies: "Python, PostgreSQL, REST API, React", benefit: "Güncel verilere daha hızlı erişim ve daha tutarlı yönetim raporlaması." }
    ]},
    process: { eyebrow: "ÇALIŞMA SÜRECİMİZ", title: "Fikirden sürdürülebilir ürüne, kontrollü ilerleyiş", lead: "Her aşamada net çıktılar, düzenli iletişim ve doğrulanabilir ilerleme.", steps: [
      { title: "İhtiyaç Analizi", text: "Hedefleri, kullanıcıları, mevcut süreçleri ve başarı ölçütlerini birlikte netleştiririz." },
      { title: "Proje Planlama", text: "Kapsamı, mimari yaklaşımı, öncelikleri ve teslim aşamalarını planlarız." },
      { title: "UI/UX Tasarımı", text: "Kullanıcı akışlarını ve arayüzleri erken doğrulanabilir prototiplere dönüştürürüz." },
      { title: "Yazılım Geliştirme", text: "Çözümü iteratif biçimde geliştirir, düzenli aralıklarla çalışan çıktılar paylaşırız." },
      { title: "Test ve Devreye Alma", text: "İşlev, güvenlik ve performans kontrollerinin ardından kontrollü geçiş sağlarız." },
      { title: "Bakım ve Geliştirme", text: "Canlı sistemi izler, geri bildirimlerle bakım ve iyileştirme planını sürdürürüz." }
    ]},
    tech: { eyebrow: "TEKNOLOJİ YAKLAŞIMI", title: "Projeye uygun, modern ve sürdürülebilir teknoloji seçimi", lead: "Araçları alışkanlığa göre değil; ölçek, güvenlik, bakım ve entegrasyon ihtiyaçlarına göre değerlendiriyoruz.", groups: [
      { title: "Frontend", items: ["HTML5", "CSS3", "JavaScript", "React", "Next.js"] },
      { title: "Backend", items: ["Node.js", "Python", ".NET", "REST API"] },
      { title: "Veritabanı", items: ["PostgreSQL", "MySQL", "MongoDB", "SQLite"] },
      { title: "Otomasyon ve Entegrasyon", items: ["API entegrasyonları", "Webhooks", "Python otomasyonu", "RPA uyumlu akışlar", "AI entegrasyonları"] },
      { title: "Bulut ve Dağıtım", items: ["GitHub", "Docker", "Bulut platformları", "CI/CD akışları"] }
    ]},
    why: { eyebrow: "NEDEN DREAMSOFT?", title: "Yazılımı teknik bir teslimat değil, uzun vadeli bir iş yatırımı olarak ele alıyoruz.", items: ["İş odaklı yazılım geliştirme", "Tek tip paket yerine özel çözüm", "Şeffaf proje iletişimi", "Modüler ve ölçeklenebilir mimari", "Güvenlik odaklı geliştirme", "Bakımı kolay kod yapısı", "Açık ve kullanılabilir dokümantasyon", "Proje sonrası teknik destek"] },
    faq: { eyebrow: "SIK SORULAN SORULAR", title: "Projeniz hakkında merak ettikleriniz", lead: "Kapsam ve teknik gereksinimler her projede farklıdır. Burada sürece ilişkin genel yanıtları bulabilirsiniz.", link: "Başka bir sorunuz mu var?", items: [
      { q: "Özel yazılım projesi ne kadar sürer?", a: "Süre; kapsam, entegrasyon sayısı, kullanıcı rolleri ve teknik belirsizliklere bağlıdır. İhtiyaç analizi sonrasında proje aşamalara ayrılır ve gerçekçi bir teslim planı paylaşılır." },
      { q: "Proje maliyeti nasıl belirlenir?", a: "Maliyet; işlev kapsamı, tasarım ihtiyacı, entegrasyonlar, güvenlik seviyesi ve destek beklentisine göre hesaplanır. Teklif öncesinde gereksinimleri netleştirerek kapsam ve maliyet ilişkisini şeffaf biçimde sunarız." },
      { q: "Mevcut sistemlerle entegrasyon yapılabilir mi?", a: "Evet. Mevcut sistem uygun bir API, veri aktarım yöntemi veya güvenli bağlantı imkânı sunuyorsa entegrasyon tasarlanabilir. Teknik uygunluk analiz aşamasında doğrulanır." },
      { q: "Küçük işletmeler için yazılım geliştiriyor musunuz?", a: "Evet. İşletmenin öncelikli problemini çözen, kontrollü bütçeyle başlayıp ihtiyaç oldukça genişleyebilen modüler kapsamlar oluşturabiliriz." },
      { q: "Proje tamamlandıktan sonra destek veriyor musunuz?", a: "Evet. Devreye alma sonrasında hata düzeltme, izleme, bakım, güvenlik güncellemeleri ve yeni geliştirmeler için ihtiyaca uygun destek modeli planlanabilir." },
      { q: "Kaynak kod teslim ediliyor mu?", a: "Kaynak kodun mülkiyeti ve teslim kapsamı proje sözleşmesinde açıkça belirlenir. Müşteriye özel geliştirilen projelerde teslim koşulları teklif aşamasında şeffaf biçimde görüşülür." },
      { q: "Yazılım daha sonra geliştirilebilir mi?", a: "Evet. Çözümleri mümkün olduğunca modüler ve sürdürülebilir tasarlayarak yeni özellik, kullanıcı ve entegrasyonların sonradan eklenebilmesini hedefleriz." },
      { q: "Veriler nasıl korunur?", a: "Erişim kontrolü, güvenli iletişim, veri minimizasyonu, yedekleme ve kayıt yönetimi gibi önlemler projenin risklerine göre planlanır. Uygulanacak güvenlik modeli kapsam ve altyapıyla birlikte belirlenir." }
    ]},
    contact: { eyebrow: "BİRLİKTE ÇALIŞALIM", title: "İş probleminizi anlatın, çözüm yolunu birlikte tasarlayalım.", lead: "Projenizin hedefini ve temel ihtiyaçlarını paylaşın. Talebiniz, e-posta uygulamanızda yapılandırılmış bir mesaj olarak hazırlanacaktır.", directTitle: "Doğrudan iletişim", directText: "Aşağıdaki bilgiler yayın öncesinde gerçek şirket bilgilerinizle değiştirilmelidir.", email: "E-posta", phone: "Telefon", address: "Adres", addressValue: "Şirket adresi buraya eklenecek" },
    form: { name: "Ad Soyad", company: "Şirket", email: "E-posta", phone: "Telefon", projectType: "Proje Türü", budget: "Tahmini Bütçe", description: "Proje Açıklaması", contactMethod: "Tercih Edilen İletişim Yöntemi", methodEmail: "E-posta", methodPhone: "Telefon", consent: "Bilgilerimin proje talebimi değerlendirmek amacıyla kullanılmasını kabul ediyorum.", submit: "Proje Talebi Gönder", note: "Bu form veri saklamaz. Gönderim, cihazınızdaki varsayılan e-posta uygulamasını açar.", select: "Seçiniz", namePlaceholder: "Adınız ve soyadınız", companyPlaceholder: "Şirket adı (isteğe bağlı)", emailPlaceholder: "ornek@sirket.com", phonePlaceholder: "+90 5xx xxx xx xx", descriptionPlaceholder: "Çözmek istediğiniz problemi, mevcut süreci ve hedefinizi kısaca anlatın...", projectTypes: ["Özel yazılım", "İş süreci otomasyonu", "Web uygulaması", "Mobil uygulama", "API / entegrasyon", "AI destekli çözüm", "Raporlama / dashboard", "Bakım ve destek", "Diğer"], budgets: ["Henüz belirlenmedi", "₺50.000 altı", "₺50.000 - ₺150.000", "₺150.000 - ₺500.000", "₺500.000 ve üzeri"], required: "Bu alan zorunludur.", invalidEmail: "Geçerli bir e-posta adresi girin.", shortDescription: "Lütfen en az 20 karakterlik bir açıklama girin.", preparing: "E-posta hazırlanıyor...", success: "E-posta uygulamanız açıldı. Açılmadıysa info@dreamsoft.example adresine doğrudan yazabilirsiniz.", mailSubject: "DreamSoft Proje Talebi", mailLabels: { name: "Ad Soyad", company: "Şirket", email: "E-posta", phone: "Telefon", projectType: "Proje Türü", budget: "Tahmini Bütçe", description: "Proje Açıklaması", contactMethod: "İletişim Tercihi" } },
    footer: { description: "İşletmeler için özel yazılım, entegrasyon ve akıllı otomasyon sistemleri geliştiriyoruz.", quick: "Hızlı Bağlantılar", services: "Hizmetler", contact: "İletişim", custom: "Özel Yazılım", automation: "Otomasyon", integrations: "Entegrasyonlar", support: "Teknik Destek", rights: "Tüm hakları saklıdır.", privacy: "Gizlilik Politikası", cookies: "Çerez Politikası", terms: "Kullanım Koşulları" },
    cookie: { title: "Gizlilik tercihiniz", text: "Bu site yalnızca dil ve çerez bildirimi tercihlerinizi cihazınızda saklar. Takip veya reklam çerezi kullanmaz.", accept: "Anladım" },
    modal: { cta: "Projenizi Konuşalım" },
    legal: {
      privacy: { title: "Gizlilik Politikası", body: ["Bu tanıtım sitesi kişisel verileri bir sunucuya göndermez veya saklamaz. İletişim formu, girdiğiniz bilgileri cihazınızdaki e-posta uygulamasına aktarır.", "Dil seçiminiz ve çerez bildirimi tercihiniz yalnızca tarayıcınızın yerel depolama alanında tutulur. Site analiz, reklam veya üçüncü taraf takip çerezi kullanmaz.", "Yayın öncesinde bu metin, şirketinizin gerçek veri işleme süreçlerine ve geçerli mevzuata göre hukuk uzmanı tarafından değerlendirilmelidir."] },
      cookies: { title: "Çerez Politikası", body: ["DreamSoft sitesi takip veya reklam çerezi kullanmaz. Yalnızca dil seçimini ve bu bildirimi kapattığınızı hatırlamak için tarayıcı yerel depolaması kullanılır.", "Bu tercihleri istediğiniz zaman tarayıcınızın site verilerini temizleyerek kaldırabilirsiniz."] },
      terms: { title: "Kullanım Koşulları", body: ["Bu sitedeki içerikler DreamSoft'un hizmet yaklaşımını genel olarak tanıtmak amacıyla sunulur. Proje örnekleri tamamlanmış müşteri işi değil, açıkça belirtilen örnek konseptlerdir.", "Teklif, süre ve teknik kapsam ancak ihtiyaç analizi ve yazılı mutabakat sonrasında bağlayıcılık kazanır. Yayın öncesinde şirket bilgileri ve hukuki metinler gözden geçirilmelidir."] }
    }
  },
  en: {
    meta: { title: "DreamSoft | Custom Software and Automation Solutions", description: "DreamSoft develops custom software, integrations, and intelligent automation solutions for businesses.", ogDescription: "Scalable custom software and intelligent automation built around your business." },
    a11y: { skip: "Skip to main content", navigation: "Main navigation", openMenu: "Open menu", closeMenu: "Close menu", language: "Language selection", backToTop: "Back to top", close: "Close" },
    nav: { home: "Home", about: "About", services: "Services", solutions: "Solutions", projects: "Projects", process: "Our Process", technologies: "Technologies", contact: "Contact", quote: "Get a Quote" },
    hero: { eyebrow: "Turning Ideas into Intelligent Software Solutions.", title: "Custom Software and Intelligent Automation for Your Business", description: "DreamSoft develops custom software, integrations, and automation systems that accelerate operations, reduce costs, and improve business efficiency.", primary: "Tell Us About Your Project", secondary: "Explore Our Services", visualLabel: "Automation workflow dashboard", visualOverline: "ACTIVE WORKFLOW", visualTitle: "Order Automation", running: "Running", nodeInput: "New Order", nodeCheck: "Data Check", nodeSync: "System Mapping", nodeReport: "Reporting", metricFlow: "Workflow health", metricSync: "Synchronization", metricErrors: "Error handling", secure: "SECURE CONNECTION", principles: ["Purpose-built", "Scalable", "Secure by design"] },
    values: { heading: "Our Core Values", items: [
      { icon: "↗", title: "Operational Efficiency", text: "Systems that reduce manual steps and let teams focus on higher-value work." },
      { icon: "◇", title: "Scalable Software", text: "Architectures designed to grow predictably with users, modules, and business volume." },
      { icon: "⌾", title: "Secure Infrastructure", text: "Solutions developed with data security, access control, and sustainable maintenance in mind." },
      { icon: "∞", title: "Long-Term Technical Support", text: "Monitoring, maintenance, and improvement support as needs evolve after launch." }
    ]},
    about: { eyebrow: "ABOUT DREAMSOFT", title: "We turn technology into real business outcomes.", lead: "We do more than build software. We understand your operations, identify bottlenecks, and design sustainable systems that adapt to your business.", link: "Explore our approach", statement: "Every project starts with a clear business problem and moves forward with a technical solution designed to create measurable value.", points: [
      { title: "Project-based approach", text: "Instead of forcing templates, we shape the scope around your goals, users, and existing systems." },
      { title: "Sustainable systems", text: "We design products that remain extensible through modular architecture, readable code, and documentation." },
      { title: "Transparent communication", text: "We communicate priorities, risks, and progress openly and consistently throughout the project." },
      { title: "Measurable business value", text: "We connect technical decisions to outcomes such as speed, cost, error rate, and operational visibility." }
    ]},
    services: { eyebrow: "OUR CAPABILITIES", title: "Technology services shaped around your needs", lead: "End-to-end software support from early concept to launch, integration, and continuous improvement.", details: "View Details", modalEyebrow: "SERVICE DETAIL", modalIntro: "This service can include", items: [
      { icon: "{ }", title: "Custom Software Development", text: "Purpose-built, modular systems for business requirements that standard packages cannot address.", detail: "We analyze business rules, user roles, and operational goals to create a product architecture aligned with your organization.", bullets: ["Requirements and scope analysis", "Modular product architecture", "Testing, documentation, and launch"] },
      { icon: "⌁", title: "Business Process Automation", text: "Reliable automations that reduce repetitive work and accelerate approval and data flows.", detail: "Manual steps are mapped and selectively automated through rule-based workflows, notifications, and system connections.", bullets: ["Process mapping", "Rule and approval engines", "Monitoring and error handling"] },
      { icon: "▱", title: "Web Application Development", text: "Fast, accessible, and secure business and customer applications for every device.", detail: "We create scalable, user-centered web applications ranging from administration tools to customer portals.", bullets: ["Responsive user interfaces", "Role-based administration", "Performance and accessibility"] },
      { icon: "▯", title: "Mobile Application Development", text: "Practical mobile experiences for field teams, customers, and operational workflows.", detail: "We choose a mobile-first, cross-platform, or native approach based on the actual business scenario.", bullets: ["Mobile product design", "Notifications and offline flows", "API and device integrations"] },
      { icon: "⇄", title: "API and System Integrations", text: "Consistent data flow across ERP, CRM, e-commerce, and third-party platforms.", detail: "Different platforms are connected through secure APIs, webhooks, and data-mapping layers within one reliable workflow.", bullets: ["REST API connections", "Data mapping and synchronization", "Logging, monitoring, and recovery"] },
      { icon: "✦", title: "Artificial Intelligence Solutions", text: "Controlled AI integrations that interpret documents, text, and operational data.", detail: "We identify where AI can create genuine value and integrate it with appropriate security and human oversight.", bullets: ["Document and text processing", "Intelligent classification and recommendations", "AI integration with existing systems"] },
      { icon: "▥", title: "Reporting and Dashboard Systems", text: "Systems that turn fragmented data into clear indicators and decision-support views.", detail: "Data from multiple sources is consolidated into current, role-appropriate, and actionable reporting experiences.", bullets: ["KPI and metric design", "Interactive dashboards", "Scheduled reports and alerts"] },
      { icon: "◌", title: "Software Maintenance and Support", text: "Support that keeps live systems secure, current, and aligned with business needs.", detail: "Applications are monitored, issues prioritized, and planned maintenance and enhancements delivered as requirements evolve.", bullets: ["Issue analysis and resolution", "Security and dependency updates", "Performance and feature improvements"] }
    ]},
    automation: { eyebrow: "INTELLIGENT AUTOMATION", title: "Let systems handle repetitive work.", lead: "Connect manual steps, fragmented data, and disconnected applications into a dependable workflow that gives your team room to focus.", diagramLabel: "Automation flow diagram from data input to reporting", workflow: "WORKFLOW ARCHITECTURE", status: "System active", list: ["Less manual work and fewer errors", "Faster approvals and turnaround", "Real-time process visibility", "Consistent data across systems"], steps: ["Data Input", "Processing", "Automation Rules", "Integration", "Reporting"], opportunities: ["Repetitive task automation", "Excel and reporting automation", "Document and data processing", "Workflow approval systems", "Customer management automation", "Production and operation monitoring", "Inventory and order management", "Email and notification automation", "Accounting and ERP integrations", "Data synchronization between platforms"] },
    industries: { eyebrow: "INDUSTRY SOLUTIONS", title: "Systems that adapt to the dynamics of your industry", lead: "Solution concepts built around your business model, processes, and growth targets instead of generic packages.", items: [
      { icon: "▦", title: "Manufacturing", text: "Production planning, work orders, quality, downtime, and efficiency monitoring systems." },
      { icon: "❉", title: "HVAC and Mechanical Contracting", text: "Quotation, estimation, costing, field progress, equipment, and maintenance applications." },
      { icon: "△", title: "Construction", text: "Project budget, progress payment, procurement, document, and site coordination systems." },
      { icon: "⇢", title: "Logistics", text: "Shipment planning, fleet and route tracking, delivery status, and operational reporting." },
      { icon: "▤", title: "Retail", text: "Inventory, order, branch operation, pricing, and sales data management." },
      { icon: "◇", title: "Professional Services", text: "Platforms that connect customer, project, task, time, quotation, and billing processes." },
      { icon: "⌑", title: "E-commerce", text: "Marketplace, order, catalog, inventory, shipping, and customer communication integrations." },
      { icon: "◫", title: "Small and Medium-Sized Businesses", text: "Right-sized solutions that consolidate fragmented workflows into extensible digital systems." }
    ]},
    projects: { eyebrow: "PROJECT APPROACHES", title: "Sample solution concepts for business problems", lead: "The following are not completed client projects. They are clearly labeled concepts illustrating systems that could be developed.", label: "Sample Project Concept", problem: "Business problem", solution: "Proposed solution", modules: "Core modules", technologies: "Possible technologies", benefit: "Expected operational benefit", view: "Explore Concept", items: [
      { code: "OPS-01", title: "Production Tracking System", problem: "Work orders, downtime, and production data are maintained across separate sources.", solution: "A web platform that collects field data centrally and displays current production status.", modules: ["Work orders", "Downtime and quality", "KPI dashboards"], technologies: "React, .NET, PostgreSQL, REST API", benefit: "Clearer production flow, faster intervention, and consistent performance data." },
      { code: "EST-02", title: "Offer and Cost Calculation Software", problem: "Complex pricing rules are managed through manual spreadsheets.", solution: "A controlled quotation application that centralizes product, labor, and margin rules.", modules: ["Price library", "Cost engine", "Quotation outputs"], technologies: "Next.js, Node.js, PostgreSQL", benefit: "Faster, more consistent quotations with a traceable revision process." },
      { code: "CRM-03", title: "Customer and Project Management Platform", problem: "Customer conversations, tasks, and project details remain scattered across channels.", solution: "A shared workspace that connects customer and project processes from sales to delivery.", modules: ["Customer records", "Projects and tasks", "Activity timeline"], technologies: "React, Python, PostgreSQL, Webhooks", benefit: "Shared visibility across teams and more controlled customer follow-up." },
      { code: "INV-04", title: "Inventory and Order Automation", problem: "Inventory discrepancies and delayed order updates occur between channels.", solution: "An integration layer that synchronizes inventory movements and order statuses across platforms.", modules: ["Inventory movements", "Order management", "Alert rules"], technologies: "Node.js, REST API, Webhooks, MySQL", benefit: "Less data entry, more consistent inventory, and faster order processing." },
      { code: "SRV-05", title: "Service and Maintenance Tracking System", problem: "Service requests, team assignments, and maintenance history cannot be tracked centrally.", solution: "A mobile-ready application that manages service operations from request to field completion.", modules: ["Service requests", "Team scheduling", "Maintenance history"], technologies: "React, .NET, SQLite, Cloud", benefit: "Faster scheduling, complete service records, and stronger field coordination." },
      { code: "BI-06", title: "Executive Reporting Dashboard", problem: "Decision data is prepared slowly from separate files and applications.", solution: "A decision-support dashboard that automatically collects, consolidates, and presents role-based indicators.", modules: ["Data connections", "KPI views", "Scheduled reports"], technologies: "Python, PostgreSQL, REST API, React", benefit: "Faster access to current data and more consistent management reporting." }
    ]},
    process: { eyebrow: "OUR PROCESS", title: "Controlled progress from idea to sustainable product", lead: "Clear outcomes, consistent communication, and verifiable progress at every stage.", steps: [
      { title: "Requirement Analysis", text: "We clarify objectives, users, current processes, and success criteria together." },
      { title: "Project Planning", text: "We plan the scope, architecture, priorities, and delivery stages." },
      { title: "UI/UX Design", text: "We turn user journeys and interfaces into prototypes that can be validated early." },
      { title: "Software Development", text: "We build iteratively and share working outputs at regular intervals." },
      { title: "Testing and Deployment", text: "We perform functional, security, and performance checks before a controlled launch." },
      { title: "Maintenance and Improvement", text: "We monitor the live system and continue maintenance and improvements based on feedback." }
    ]},
    tech: { eyebrow: "TECHNOLOGY APPROACH", title: "Modern, sustainable technology selected for the project", lead: "We assess tools based on scale, security, maintenance, and integration needs rather than habit.", groups: [
      { title: "Frontend", items: ["HTML5", "CSS3", "JavaScript", "React", "Next.js"] },
      { title: "Backend", items: ["Node.js", "Python", ".NET", "REST API"] },
      { title: "Database", items: ["PostgreSQL", "MySQL", "MongoDB", "SQLite"] },
      { title: "Automation and Integration", items: ["API integrations", "Webhooks", "Python automation", "RPA-compatible workflows", "AI integrations"] },
      { title: "Cloud and Deployment", items: ["GitHub", "Docker", "Cloud platforms", "CI/CD workflows"] }
    ]},
    why: { eyebrow: "WHY DREAMSOFT?", title: "We treat software as a long-term business investment, not just a technical deliverable.", items: ["Business-oriented software development", "Custom solutions instead of one-size-fits-all packages", "Transparent project communication", "Modular and scalable architecture", "Security-focused development", "Maintainable code structure", "Clear, practical documentation", "Post-project technical support"] },
    faq: { eyebrow: "FREQUENTLY ASKED QUESTIONS", title: "What you may want to know about your project", lead: "Scope and technical requirements differ for every project. These answers provide general guidance about the process.", link: "Have another question?", items: [
      { q: "How long does a custom software project take?", a: "Duration depends on scope, integration count, user roles, and technical uncertainty. After requirement analysis, the project is divided into stages and a realistic delivery plan is provided." },
      { q: "How is project pricing determined?", a: "Pricing is based on functional scope, design needs, integrations, security level, and support expectations. We clarify requirements before the proposal and explain the relationship between scope and cost transparently." },
      { q: "Can you integrate with existing systems?", a: "Yes. Integration can be designed when an existing system provides a suitable API, data transfer method, or secure connection option. Technical feasibility is confirmed during analysis." },
      { q: "Do you develop software for small businesses?", a: "Yes. We can define a modular scope that addresses the highest-priority problem within a controlled budget and expands as needs grow." },
      { q: "Do you provide support after project completion?", a: "Yes. A suitable support model can cover issue resolution, monitoring, maintenance, security updates, and further development after launch." },
      { q: "Is the source code delivered?", a: "Source code ownership and delivery scope are defined clearly in the project agreement. For custom projects, delivery terms are discussed transparently during the proposal stage." },
      { q: "Can the software be expanded later?", a: "Yes. We aim to design solutions with modular, sustainable foundations so new features, users, and integrations can be added later." },
      { q: "How is data protected?", a: "Controls such as access management, secure communication, data minimization, backups, and logging are planned according to project risk. The final security model depends on scope and infrastructure." }
    ]},
    contact: { eyebrow: "LET'S WORK TOGETHER", title: "Tell us about your business problem, and let’s design the path forward.", lead: "Share your project goals and core needs. Your request will be prepared as a structured message in your email application.", directTitle: "Direct contact", directText: "Replace the placeholder information below with verified company details before publishing.", email: "Email", phone: "Phone", address: "Address", addressValue: "Company address to be added here" },
    form: { name: "Name", company: "Company", email: "Email", phone: "Phone", projectType: "Project Type", budget: "Estimated Budget", description: "Project Description", contactMethod: "Preferred Contact Method", methodEmail: "Email", methodPhone: "Phone", consent: "I agree that my information may be used to evaluate my project request.", submit: "Submit Project Request", note: "This form stores no data. Submitting opens the default email application on your device.", select: "Select", namePlaceholder: "Your full name", companyPlaceholder: "Company name (optional)", emailPlaceholder: "name@company.com", phonePlaceholder: "+1 000 000 0000", descriptionPlaceholder: "Briefly describe the problem, your current process, and the outcome you need...", projectTypes: ["Custom software", "Business process automation", "Web application", "Mobile application", "API / integration", "AI-powered solution", "Reporting / dashboard", "Maintenance and support", "Other"], budgets: ["Not determined yet", "Under $5,000", "$5,000 - $15,000", "$15,000 - $50,000", "$50,000 and above"], required: "This field is required.", invalidEmail: "Enter a valid email address.", shortDescription: "Please enter a description of at least 20 characters.", preparing: "Preparing your email...", success: "Your email application has been opened. If it did not open, email info@dreamsoft.example directly.", mailSubject: "DreamSoft Project Request", mailLabels: { name: "Name", company: "Company", email: "Email", phone: "Phone", projectType: "Project Type", budget: "Estimated Budget", description: "Project Description", contactMethod: "Contact Preference" } },
    footer: { description: "We develop custom software, integrations, and intelligent automation systems for businesses.", quick: "Quick Links", services: "Services", contact: "Contact", custom: "Custom Software", automation: "Automation", integrations: "Integrations", support: "Technical Support", rights: "All rights reserved.", privacy: "Privacy Policy", cookies: "Cookie Policy", terms: "Terms of Use" },
    cookie: { title: "Your privacy preference", text: "This site only stores your language and cookie notice preferences on your device. It uses no tracking or advertising cookies.", accept: "Understood" },
    modal: { cta: "Discuss Your Project" },
    legal: {
      privacy: { title: "Privacy Policy", body: ["This presentation website does not send personal information to or store it on a server. The contact form passes the information you enter to the email application on your device.", "Your language and cookie notice preferences are stored only in local browser storage. The site uses no analytics, advertising, or third-party tracking cookies.", "Before publication, this text should be reviewed by a legal professional against your company’s actual data practices and applicable law."] },
      cookies: { title: "Cookie Policy", body: ["The DreamSoft website uses no tracking or advertising cookies. Browser local storage is used only to remember your language selection and that you dismissed this notice.", "You can remove these preferences at any time by clearing site data in your browser."] },
      terms: { title: "Terms of Use", body: ["Content on this site provides a general introduction to DreamSoft’s service approach. Project examples are clearly identified concepts, not completed client work.", "Proposals, timelines, and technical scope become binding only after requirement analysis and written agreement. Company details and legal content should be reviewed before publication."] }
    }
  }
};
